/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicomecocos;

import data.*;

/**
 *
 * @author alejandrocq
 */
public class ComecocosFrame extends javax.swing.JFrame {
    
    /**
     * Inicializa la ventana del juego, establece el título de la misma como "Pacman" y inicializa el contador de puntuación a cero.
     */
    public ComecocosFrame() {
        initComponents();
        this.setTitle("Pacman");
        areaPuntuacion.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laberintoFrame1 = new LaberintoFrame(this);
        jLabel1 = new javax.swing.JLabel();
        areaPuntuacion = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuJuego = new javax.swing.JMenu();
        juegoNuevo = new javax.swing.JMenuItem();
        juegoPausar = new javax.swing.JMenuItem();
        juegoSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 631));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout laberintoFrame1Layout = new javax.swing.GroupLayout(laberintoFrame1);
        laberintoFrame1.setLayout(laberintoFrame1Layout);
        laberintoFrame1Layout.setHorizontalGroup(
            laberintoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        laberintoFrame1Layout.setVerticalGroup(
            laberintoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jLabel1.setText("Puntuación:");

        areaPuntuacion.setEditable(false);
        areaPuntuacion.setText("0");
        areaPuntuacion.setToolTipText("");
        areaPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaPuntuacionActionPerformed(evt);
            }
        });

        menuJuego.setText("Juego");

        juegoNuevo.setText("Nuevo");
        juegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoNuevoActionPerformed(evt);
            }
        });
        menuJuego.add(juegoNuevo);

        juegoPausar.setText("Pausar");
        juegoPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoPausarActionPerformed(evt);
            }
        });
        menuJuego.add(juegoPausar);

        juegoSalir.setText("Salir");
        juegoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoSalirActionPerformed(evt);
            }
        });
        menuJuego.add(juegoSalir);

        jMenuBar1.add(menuJuego);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(laberintoFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(areaPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(laberintoFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(areaPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que cierra el programa cuando se hace clic en la opción "Salir" del menú Juego.
     * @param evt Objeto de la clase java.awt.event.ActionEvent.
     */
    private void juegoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_juegoSalirActionPerformed
    /**
     * Método que cierra el programa cuando se hace clic en el botón de cerrar ventana.
     * @param evt Objeto de la clase java.awt.event.WindowEvent.
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
    /**
     * Este método no realiza ninguna acción. Fue creado automáticamente por Netbeans.
     * @param evt Objeto de la clase java.awt.event.ActionEvent.
     */
    private void areaPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaPuntuacionActionPerformed
        // Sin acciones.
    }//GEN-LAST:event_areaPuntuacionActionPerformed
    /**
     * Método que llama al método reiniciar() de la clase LaberintoFrame cuando se hace clic en la opción "Nuevo" del menú Juego.
     * @param evt Objeto de la clase java.awt.event.ActionEvent.
     */
    private void juegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoNuevoActionPerformed
        laberintoFrame1.reiniciar();
    }//GEN-LAST:event_juegoNuevoActionPerformed
    /**
     * Método que llama al método pausa() de la clase LaberintoFrame cuando se hace clic en la opción "Pausa" del menú Juego.
     * @param evt Objeto de la clase java.awt.event.ActionEvent.
     */
    private void juegoPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoPausarActionPerformed
        laberintoFrame1.pausa();
    }//GEN-LAST:event_juegoPausarActionPerformed

    
    /**
     * Se encarga de actualizar la puntuación en el elemento areaPuntuacion.
     * @param puntos Puntos a sumar al total.
     */
    public void puntuacion(int puntos){
        if(areaPuntuacion!=null)
            areaPuntuacion.setText(""+puntos);
    }
    
    
    /**
     * Método main de la clase ComecocosFrame.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComecocosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaPuntuacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem juegoNuevo;
    private javax.swing.JMenuItem juegoPausar;
    private javax.swing.JMenuItem juegoSalir;
    private guicomecocos.LaberintoFrame laberintoFrame1;
    private javax.swing.JMenu menuJuego;
    // End of variables declaration//GEN-END:variables
}
