/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guicomecocos;

import data.*;

/**
 *
 * @author alejandrocq
 */
public class ComecocosFrame extends javax.swing.JFrame {

    private Rejilla laberinto;
    private Mueve mueve;
    
    /**
     * Creates new form Comecocos
     */
    public ComecocosFrame() {
        initComponents();
        laberinto = new Rejilla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laberintoFrame1 = new LaberintoFrame (this);
        jMenuBar1 = new javax.swing.JMenuBar();
        menuJuego = new javax.swing.JMenu();
        juegoNuevo = new javax.swing.JMenuItem();
        juegoPausar = new javax.swing.JMenuItem();
        juegoSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout laberintoFrame1Layout = new javax.swing.GroupLayout(laberintoFrame1);
        laberintoFrame1.setLayout(laberintoFrame1Layout);
        laberintoFrame1Layout.setHorizontalGroup(
            laberintoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        laberintoFrame1Layout.setVerticalGroup(
            laberintoFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        menuJuego.setText("Juego");

        juegoNuevo.setText("Nuevo");
        menuJuego.add(juegoNuevo);

        juegoPausar.setText("Pausar");
        menuJuego.add(juegoPausar);

        juegoSalir.setText("Salir");
        juegoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoSalirActionPerformed(evt);
            }
        });
        menuJuego.add(juegoSalir);

        jMenuBar1.add(menuJuego);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(laberintoFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(laberintoFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juegoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_juegoSalirActionPerformed

    
    public Rejilla getRejilla() {
        return laberinto;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComecocosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem juegoNuevo;
    private javax.swing.JMenuItem juegoPausar;
    private javax.swing.JMenuItem juegoSalir;
    private guicomecocos.LaberintoFrame laberintoFrame1;
    private javax.swing.JMenu menuJuego;
    // End of variables declaration//GEN-END:variables
}
